#!/usr/bin/env python3
"""
AI Ideation Agent for workflow orchestrator.

Handles ideation requests by analyzing requirements and generating technical specifications.
Uses placeholder AI logic that can be replaced with actual AI services.

Communicates via qwe messaging system.
"""
import argparse
import requests
import time
import sys
import logging
import json

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def fetch_messages(server):
    """Fetch messages from qwe server."""
    url = server.rstrip('/') + '/api/v1/agents/messages'
    try:
        resp = requests.get(url, timeout=10)
        resp.raise_for_status()
        return resp.json().get('messages', [])
    except requests.RequestException as e:
        logger.error(f"Error fetching messages: {e}")
        return []

def send_message(server, channel, message, agent_name):
    """Send message to qwe server."""
    url = server.rstrip('/') + '/api/v1/agents/message'
    payload = {
        'channel': channel,
        'message': message,
        'agent': agent_name
    }
    try:
        resp = requests.post(url, json=payload, timeout=10)
        resp.raise_for_status()
        logger.info(f"Sent message: {message}")
        return resp
    except requests.RequestException as e:
        logger.error(f"Failed to send message: {e}")
        return None

def analyze_requirements(requirements_text):
    """
    Placeholder AI function to analyze requirements and generate technical specs.
    Replace with actual AI service call.
    """
    try:
        # Simulate AI processing
        logger.info("Analyzing requirements with AI...")
        time.sleep(1)  # Simulate processing time

        # Placeholder response - in real implementation, call AI API
        specs = f"""
Technical Specifications for: {requirements_text}

1. Architecture:
   - Microservices design
   - RESTful APIs
   - Database: PostgreSQL

2. Components:
   - Frontend: React.js
   - Backend: Python/FastAPI
   - Authentication: JWT

3. Security:
   - Input validation
   - HTTPS encryption
   - Role-based access control

4. Performance:
   - Response time < 200ms
   - Concurrent users: 1000+

Generated by AI Ideation Agent
"""
        return specs.strip()
    except Exception as e:
        logger.error(f"Error in AI analysis: {e}")
        return f"Error generating specs: {str(e)}"

def process_ideation_request(message_text, agent_name):
    """Process an ideation request message."""
    try:
        # Extract requirements from message (simple parsing)
        if "ideation:" in message_text.lower():
            requirements = message_text.split("ideation:", 1)[1].strip()
        else:
            requirements = message_text.strip()

        logger.info(f"Processing ideation request: {requirements}")

        # Generate technical specs
        specs = analyze_requirements(requirements)

        # Format response
        response = f"Ideation complete for '{requirements}':\n{specs}"

        return response
    except Exception as e:
        logger.error(f"Error processing ideation request: {e}")
        return f"Error processing request: {str(e)}"

def main():
    parser = argparse.ArgumentParser(description='AI Ideation Agent')
    parser.add_argument('--server', default='http://localhost:9001', help='QWE server URL')
    parser.add_argument('--channel', default='ideation', help='Channel to listen on')
    parser.add_argument('--interval', type=float, default=2.0, help='Polling interval in seconds')
    parser.add_argument('--agent-name', default='ai-ideation-agent', help='Agent name')
    args = parser.parse_args()

    server = args.server
    channel = args.channel
    interval = args.interval
    agent_name = args.agent_name

    seen = set()
    logger.info(f"Starting {agent_name}. Server={server} channel={channel} interval={interval}s")

    try:
        while True:
            try:
                messages = fetch_messages(server)
            except Exception as ex:
                logger.error(f"Error in main loop: {ex}")
                time.sleep(interval)
                continue

            for m in messages:
                # Use message ID as identifier to avoid duplicates
                msg_id = m.get('id')
                if msg_id in seen:
                    continue
                seen.add(msg_id)

                msg_channel = m.get('channel', '')
                msg_text = m.get('message', '')
                msg_agent = m.get('agent', '')

                # Only process messages on our channel and not from ourselves
                if msg_channel == channel and msg_agent != agent_name:
                    logger.info(f"Received message: {msg_text}")

                    # Check if it's an ideation request
                    if 'ideation' in msg_text.lower() or channel == 'ideation':
                        response = process_ideation_request(msg_text, agent_name)

                        # Send response back
                        send_message(server, channel, response, agent_name)

            time.sleep(interval)
    except KeyboardInterrupt:
        logger.info(f"Shutting down {agent_name}")
        sys.exit(0)
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        sys.exit(1)

if __name__ == '__main__':
    main()